name: Banxico Reports Scraper

on:
  workflow_dispatch:      # Manual trigger
  push:
    branches: [ main ]   
  schedule:
    - cron: '0 0 3 * *'         # Library updates - 3rd of each month
    - cron: '0 0 28,29 */3 *'   # Quarterly reports - 28th-29th every 3 months
    - cron: '0 0 11-15 */3 *'   # Regional reports - 11th-15th every 3 months

jobs:
  banxico-reports:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run Library Updates
      if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 0 3 * *'
      run: python scripts/library_updates.py
    
    - name: Run Quarterly Reports
      if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 0 28,29 */3 *'
      run: python "scripts/informes trimestrales.py"
    
    - name: Run Regional Reports
      if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 0 11-15 */3 *'
      run: python "scripts/informes regionales.py"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: banxico-reports
        path: 'reports and files/'
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add "reports and files/"
        timestamp=$(date -u)
        git commit -m "Auto-update reports: ${timestamp}" || exit 0
        git push