name: Banxico Reports Scraper

on:
  workflow_dispatch:      # Manual trigger
  push:
    branches: [ main ]   
  schedule:
    - cron: '0 6 3 * *'         # Library updates - 3rd of each month at 00:00 Mexico time (06:00 UTC)
    - cron: '0 6 28,29 */3 *'   # Quarterly reports - 28th-29th every 3 months at 00:00 Mexico time
    - cron: '0 6 11-15 */3 *'   # Regional reports - 11th-15th every 3 months at 00:00 Mexico time

jobs:
  banxico-reports:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run Library Updates
      if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 0 3 * *'
      run: python scripts/library_updates-monthly.py
    
    - name: Upload Library Updates Artifacts
      if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 0 3 * *'
      uses: actions/upload-artifact@v3
      with:
        name: library-updates
        path: 'reports and files/banxico_library_updates/'
    
    - name: Run Quarterly Reports
      if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 0 28,29 */3 *'
      run: python "scripts/quarterly_reports-quarter.py"
    
    - name: Upload Quarterly Reports Artifacts
      if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 0 28,29 */3 *'
      uses: actions/upload-artifact@v3
      with:
        name: quarterly-reports
        path: 'reports and files/banxico_quarterly_reports/'
    
    - name: Run Regional Reports
      if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 0 11-15 */3 *'
      run: python "scripts/regional_reports-quarter"
    
    - name: Upload Regional Reports Artifacts
      if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 0 11-15 */3 *'
      uses: actions/upload-artifact@v3
      with:
        name: regional-reports
        path: 'reports and files/banxico_regional_reports/'
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add "reports and files/"
        timestamp=$(date -u)
        git commit -m "Auto-update reports: ${timestamp}" || exit 0
        git push