name: Banxico Reports Scraper

on:
  workflow_dispatch:      # Manual trigger
  push:
    branches: [ main ]   
  schedule:
    - cron: '0 0 3 * *'         # Library updates - 3rd of each month
    - cron: '0 0 28,29 */3 *'   # Quarterly reports - 28th-29th every 3 months
    - cron: '0 0 11-15 */3 *'   # Regional reports - 11th-15th every 3 months

jobs:
  library-updates:
    if: github.event.schedule != '0 0 28,29 */3 *' && github.event.schedule != '0 0 11-15 */3 *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python scripts/library_updates.py
      - uses: actions/upload-artifact@v3
        with:
          name: library-updates
          path: 'reports and files/banxico_library_updates/'
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add "reports and files/banxico_library_updates/"
          git commit -m "Auto-update library reports" || exit 0
          git push

  quarterly-reports:
    if: github.event.schedule == '0 0 28,29 */3 *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python "scripts/informes trimestrales.py"
      - uses: actions/upload-artifact@v3
        with:
          name: quarterly-reports
          path: 'reports and files/banxico_quarterly_reports/'
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add "reports and files/banxico_quarterly_reports/"
          git commit -m "Auto-update quarterly reports" || exit 0
          git push

  regional-reports:
    if: github.event.schedule == '0 0 11-15 */3 *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python "scripts/informes regionales.py"
      - uses: actions/upload-artifact@v3
        with:
          name: regional-reports
          path: 'reports and files/banxico_regional_reports/'
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add "reports and files/banxico_regional_reports/"
          git commit -m "Auto-update regional reports" || exit 0
          git push