# name: Banxico Reports Scraper

# on:
#   schedule:
#     - cron: '0 * * * *'  # Hourly
#   workflow_dispatch:      # Manual trigger
#   push:
#     branches: [ main ]   # Push trigger

# jobs:
#   run-script:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.10'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run Python script
#       env:
#         actkey: ${{ secrets.DONALOCA }}
#       run: |
#         python scripts/library_updates.py

#     - name: Upload artifacts
#       if: success()
#       uses: actions/upload-artifact@v3
#       with:
#         name: downloaded-reports
#         path: 'reports and files/'

#     - name: Commit and push changes
#       run: |
#         git config --global user.name 'github-actions[bot]'
#         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
#         git add "reports and files/"
#         timestamp=$(date -u)
#         git commit -m "Auto-update reports: ${timestamp}" || exit 0
#         git push
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


name: Banxico Reports Scraper

on:
  workflow_dispatch:      # Manual trigger
  push:
    branches: [ main ]   
  schedule:
    - cron: '0 0 3 * *'         # Library updates
    - cron: '0 0 28,29 */3 *'   # Quarterly reports
    - cron: '0 0 11-15 */3 *'   # Regional reports

jobs:
  update-reports:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create and switch to autoupdates branch
      run: |
        git fetch origin
        git checkout -B autoupdates
        git pull origin autoupdates || true

    - name: Run scripts based on schedule
      run: |
        python scripts/library_updates.py
        python "scripts/informes trimestrales.py"
        python "scripts/informes regionales.py"

    - name: Commit and push to autoupdates
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add "reports and files/"
        timestamp=$(date -u)
        git commit -m "Auto-update reports: ${timestamp}" || exit 0
        git push -u origin autoupdates

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.DONALOCA }}
        branch: autoupdates
        base: main
        title: 'Auto Update: New Reports Available'
        body: |
          Automated report updates from scheduled workflow
          
          Please review the changes before merging.
        labels: automated-pr