name: Banxico Reports Scraper

on:
  workflow_dispatch:      # Manual trigger
  push:
    branches: [ main ]   
  schedule:
    - cron: '0 0 3 * *'         # Library updates
    - cron: '0 0 28,29 */3 *'   # Quarterly reports
    - cron: '0 0 11-15 */3 *'   # Regional reports

jobs:
  update-reports:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create and switch to autoupdates branch
      run: |
        git fetch origin || true
        git checkout -B autoupdates origin/main || git checkout -b autoupdates

    - name: Run scripts
      run: |
        python scripts/library_updates.py
        python "scripts/informes trimestrales.py"
        python "scripts/informes regionales.py"

    - name: Commit and push changes
      run: |
        git add "reports and files/"
        timestamp=$(date -u)
        git commit -m "Auto-update reports: ${timestamp}" || true
        git push -f origin autoupdates

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: autoupdates
        base: main
        title: 'Auto Update: New Reports Available'
        body: 'Automated report updates from scheduled workflow'